<a href="https://colab.research.google.com/github/yash99-bot/Drive__car/blob/main/Learner_Demographics_and_Course_Enrollment_Behavior_Analysis_on_EduPro.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [ ]:
data = pd.read_excel(r'EduPro Online Platform (1).xlsx')
data.head()
data.isnull().sum()
data.duplicated().sum()
data.columns

Index(['UserID', 'UserName', 'Age', 'Gender', 'Email'], dtype='object')

In [ ]:
data['UserID'].value_counts()
data["Age"].between(0, 15).sum()
data["Age"].between(15, 30).sum()
data["Age"].between(50, 75).sum()
pd.cut(data["Age"], bins=[0, 15, 50, 75], labels=["Low", "Medium", "High"]).value_counts()

Age
Medium    2845
Low        155
High         0
Name: count, dtype: int64

In [ ]:
data['Gender'].unique()
data['Gender'].value_counts()

Gender
Female    1520
Male      1480
Name: count, dtype: int64

In [ ]:
df2 = pd.read_excel(r'EduPro Online Platform (1).xlsx', sheet_name=1)
df2.head()
df2.isnull().sum()
df2.duplicated().sum()
df2.columns

Index(['TeacherID', 'TeacherName', 'Age', 'Gender', 'Expertise',
       'YearsOfExperience', 'TeacherRating'],
      dtype='object')

In [ ]:
df2['TeacherRating'].value_counts()
#df2['TeacherRating'].unique()
#df2['TeacherID'].value_counts()
df2["TeacherRating"].between(1, 2).sum()
df2["TeacherRating"].between(2, 3).sum()
df2["TeacherRating"].between(3, 4).sum()
df2["TeacherRating"].between(4, 5).sum()
pd.cut(df2["TeacherRating"], bins=[1, 2, 3, 4, 5], labels=["Low", "Medium", "High" ,"max"]).value_counts()

TeacherRating
High      28
Medium    12
max       11
Low        9
Name: count, dtype: int64

In [ ]:
#df2["TeacherRating"].between(1, 2)
teacher_names = df2.loc[df2["TeacherRating"].between(1, 2), "TeacherName"]
teacher_names1 = df2.loc[df2["TeacherRating"].between(2, 3), "TeacherName"]
teacher_names2 = df2.loc[df2["TeacherRating"].between(3, 4), "TeacherName"]
teacher_names3 = df2.loc[df2["TeacherRating"].between(4, 5), "TeacherName"]
print(teacher_names)

2        Amber Torres
26     Laurie Michael
27     Timothy Bailey
30      Brenda Mercer
35      Brenda Mclean
42      John Williams
44    Emily Gutierrez
46       Brad Griffin
50        John Obrien
Name: TeacherName, dtype: object

In [ ]:
df2["YearsOfExperience"].between(0, 5).sum()
df2["YearsOfExperience"].between(5, 10).sum()
df2["YearsOfExperience"].between(10, 15).sum()
df2["YearsOfExperience"].between(15, 20).sum()
pd.cut(df2["YearsOfExperience"], bins=[0, 5, 10, 15, 20], labels=["Low", "Medium", "High" ,"max"]).value_counts()

YearsOfExperience
Low       28
Medium    23
High       7
max        0
Name: count, dtype: int64

In [ ]:
df3 = pd.read_excel(r'EduPro Online Platform (1).xlsx', sheet_name=2)
df3.head()
df3.isnull().sum()
df3.duplicated().sum()
df3.columns

Index(['CourseID', 'CourseName', 'CourseCategory', 'CourseType', 'CourseLevel',
       'CoursePrice', 'CourseDuration', 'CourseRating'],
      dtype='object')

In [ ]:
df3['CourseID'].value_counts()
df3['CourseCategory'].unique()
df3['CourseCategory'].value_counts()
avg_ratings = df3.groupby("CourseCategory")["CourseRating"].mean()
print(avg_ratings)

CourseCategory
Artificial Intelligence    3.036
Business                   2.688
Cybersecurity              2.902
Data Science               3.316
Design                     3.162
Digital Marketing          3.656
Finance                    3.010
Machine Learning           2.658
Marketing                  3.722
Programming                3.036
Project Management         3.142
Web Development            2.846
Name: CourseRating, dtype: float64